Feature/sentence
K-HBD/Consolation-Server pull request #4
Opened 2022-06-26 04:07 UTC by honghyunin

# 작업 사항
_이번 PR에서는 현재 위로해주는 말을 조회하는 로직에 대한 논의가 필요한 거 같습니다. 코드 리뷰 이후 이에 대한 의견 남겨주시면 감사하겠습니다!_

## Comments of Commit

### ADD | Sentence
- ADD | Sentence Entity 생성 : 특정 감정에 따른 위로의 말(Sentence)을 DB에 저장하여 감정 별로 위로의 말이 나올 수 있도록 Entity를 생성
- ADD | Use Enum 추가 : 나왔던 Sentence가 또 나오는 일을 최소화하기 위해 추가한 Enum입니다.
- ADD | SentenceService / Impl 추가 : 추후에 배포를 한 상태에서 Sentence를 추가할 수도 있기에 Sentence 추가 로직을 작
- ADD | SentenceController 추가 : 추후에 Sentence를 추가하기 위한 Controller
- ADD | SentenceCustomRepository / Impl 추가 : 사용되지 않은 특정 감정의 Sentence를 하나 조회하기 위한 쿼리 작성
- ADD | SentenceDto 추가 : Sentence 추가에 필요한 Dto 추가
- ADD | SentenceCustomRepository / Impl : 모든 Sentence가 USED_LETTER로 변경되었을 때 Sentence를 사용할 수 있도록 모든 Sentence의 Use를  NOT_USED_LETTER로 변경하는 쿼리 작성
- ADD | SentenceService findSentence 추가 : Sentence를 조회하는 메서드 추가
               .etc : 로직상 findSentence 부분에서 모든 Sentence가 USED_LETTER로 변경되었을 때  모든 Sentence의 Use를 NOT_USED_LETTER로 다시 업데이트 해야하는 부분이 존재하는데 이 부분에 대한 용우님의 생각이 궁금합니다.
- ADD | SetSentence : Sentence를 매번 추가할 순 없기에 미리 몇 가지의 Sentence를 추가하기 위한 설정 파일

### ADD | querydsl 
- ADD | querydsl 의존성과 설정 추가 : querydsl 사용에 필요한 의존성과 설정을 추가
- ADD | querydsl 전역 사용 설정 추가 : JPAQueryFactory를 querydsl Repository 전역적으로 사용하기 위한 설정
- ADD | QuerydslConfig JPAUpdateClause 추가 : JPAUpdateClause를 querydsl Repository 전역적으로 사용하기 위한 설정

### ADD | DynamicUpdate 추가
- Sentence의 컬럼 중 Use만 업데이트하기 때문에 변경된 컬럼만 업데이트하는 DynamicUpdate 어노테이션을 추가

### Logic에 대한 논의
앱에서 감정에 맞는 위로의 말을 조회해올 때의 로직입니다.
해당 로직을 이렇게 작성하게 된 이유는 사용자가 같은 위로의 문구를 보는 것보다는, 다른 문구를 보는 것이 더 좋을 것 같아 문구의 중복성을 최대한 낮추고자 한 것입니다. 이를 해결하기 위한 방법을 현재 로직을 구상한 것이었고, 더 나은 방법이 있어 조언해주시면 감사하겠습니다!

1. 이미지를 통해 모델에서 나온 감정이 SAD라고 했을 때 DB에서 Sentence의 Emotion이 SAD인 글만 조회함.
2. 이때 조회된 글은 NOT_USED_LETTER이기에 조회된 것이므로, 현재 조회되어 사용됬으므로 USED_LETTER로 변경
4. NOT_USED_LETTER 인 글만 조회하는데, 조회한 글의 결과값이 null일 경우 더 이상 NOT_USED_LETTER인 글이 없어서 결과값이 없다는 뜻이고 따라서 모든 글이 USE_LETTER인 경우란 뜻이기에 전부 NOT_USER_LETTER로 변경하고 글을 조회해서 결과 값을 반환

__동시성 문제가 발생할 것 같아 비관적 Lock을 사용하고자 하는데 어떠신가요? 또는 해당 로직을 변경할 필요가 있을까요?__

2022-06-27 02:19 UTC, Sinawe4 commented
코드리뷰를 진행하다가 문득 든 생각입니다만, 저희 앱 자체에서는 유저 로그인이 존재하지 않는 것으로 알고 있습니다.
> 해당 로직을 이렇게 작성하게 된 이유는 사용자가 같은 위로의 문구를 보는 것보다는, 다른 문구를 보는 것이 더 좋을 것 같아 문구의 중복성을 최대한 낮추고자 한 것입니다. 이를 해결하기 위한 방법을 현재 로직을 구상한 것이었고, 더 나은 방법이 있어 조언해주시면 감사하겠습니다!

해당 Comment에서는 "사용자가 같은 위로의 문구를 보는 것을 방지하기 위해" 라고 말씀을 해주셨는데.
사용자의 구분을 어떤식으로 진행하죠?? A라는 문구를 한번 본 사용자인지, 한번도 보지 못한 사용자인지 구분하는 방법이 궁금하네요

2022-06-27 05:58 UTC, honghyunin commented
> 코드 리뷰를 진행하다가 문득 든 생각입니다만, 저희 앱 자체에서는 유저 로그인이 존재하지 않는 것으로 알고 있습니다.
> 
> > 해당 로직을 이렇게 작성하게 된 이유는 사용자가 같은 위로의 문구를 보는 것보다는, 다른 문구를 보는 것이 더 좋을 것 같아 문구의 중복성을 최대한 낮추고자 한 것입니다. 이를 해결하기 위한 방법을 현재 로직을 구상한 것이었고, 더 나은 방법이 있어 조언해 주시면 감사하겠습니다!
> 
> 해당 Comment에서는 "사용자가 같은 위로의 문구를 보는 것을 방지하기 위해"라고 말씀을 해주셨는데. 사용자의 구분을 어떤 식으로 진행하죠?? A라는 문구를 한번 본 사용자인지, 한 번도 보지 못한 사용자인지 구분하는 방법이 궁금하네요

용우님 말씀대로 특정 사용자가 어떤 글을 읽고 안 읽고는 없습니다.

사실 지금 로직에서는 __특정 유저가 읽지 않은 문구를 보여준다__ 이를 이루고 있지 않습니다. 그저 A 유저가 읽기만 하면 읽음으로 처리되고 따라서 이 유저가 읽지 않은 문구까지 다른 유저가 읽게되면 A유저는 다른 유저가 읽어버린 문구를 볼 수 없는거죠.

다시 생각해보니 User Entity를 생성하고 User와 Sentence의 관계를 N:M, 1:N N:1로 풀어야 할 것 같습니다.
따라서 테이블이 총 User, User_Sentence, Sentence 이렇게 두고

User_sentence에서 특정 유저가 읽었는 지 안 읽었는 지를 체크해야할 것 같습니다.

현재 로직은 용우님의 의견을 묻기 위해 PR을 올린 것이였으며, 제가 봐도 말도 안되는 로직인 것 같습니다.
지금 하고 있는 다른 작업을 마친 후 바로 해당 로직 수정하겠습니다.

2022-06-27 07:10 UTC, Sinawe4 commented
> 



> > 코드 리뷰를 진행하다가 문득 든 생각입니다만, 저희 앱 자체에서는 유저 로그인이 존재하지 않는 것으로 알고 있습니다.
> > > 해당 로직을 이렇게 작성하게 된 이유는 사용자가 같은 위로의 문구를 보는 것보다는, 다른 문구를 보는 것이 더 좋을 것 같아 문구의 중복성을 최대한 낮추고자 한 것입니다. 이를 해결하기 위한 방법을 현재 로직을 구상한 것이었고, 더 나은 방법이 있어 조언해 주시면 감사하겠습니다!
> > 
> > 
> > 해당 Comment에서는 "사용자가 같은 위로의 문구를 보는 것을 방지하기 위해"라고 말씀을 해주셨는데. 사용자의 구분을 어떤 식으로 진행하죠?? A라는 문구를 한번 본 사용자인지, 한 번도 보지 못한 사용자인지 구분하는 방법이 궁금하네요
> 
> 용우님 말씀대로 특정 사용자가 어떤 글을 읽고 안 읽고는 없습니다.
> 
> 사실 지금 로직에서는 **특정 유저가 읽지 않은 문구를 보여준다** 이를 이루고 있지 않습니다. 그저 A 유저가 읽기만 하면 읽음으로 처리되고 따라서 이 유저가 읽지 않은 문구까지 다른 유저가 읽게되면 A유저는 다른 유저가 읽어버린 문구를 볼 수 없는거죠.
> 
> 다시 생각해보니 User Entity를 생성하고 User와 Sentence의 관계를 N:M, 1:N N:1로 풀어야 할 것 같습니다. 따라서 테이블이 총 User, User_Sentence, Sentence 이렇게 두고
> 
> User_sentence에서 특정 유저가 읽었는 지 안 읽었는 지를 체크해야할 것 같습니다.
> 
> 현재 로직은 용우님의 의견을 묻기 위해 PR을 올린 것이였으며, 제가 봐도 말도 안되는 로직인 것 같습니다. 지금 하고 있는 다른 작업을 마친 후 바로 해당 로직 수정하겠습니다.

UserEntity가 생기게되면 필연적으로 로그인/회원가입 기능이 존재하게 되지않나요?
저는 차라리 읽고, 안읽고 여부에 상관없이 그냥 랜덤으로 내보내는 방법이 제일 편할꺼같기도합니다.

2022-06-27 07:12 UTC, Sinawe4 requested changes
전체적인 로직의 변경이 필요할꺼같습니다.
당장은 코드리뷰의 의미가 없을꺼같아 Request changes 하겠습니다.

2022-06-27 13:49 UTC, honghyunin commented
> UserEntity가 생기게되면 필연적으로 로그인/회원가입 기능이 존재하게 되지않나요? 저는 차라리 읽고, 안읽고 여부에 상관없이 그냥 랜덤으로 내보내는 방법이 제일 편할꺼같기도합니다.

제가 생각이 짧았네요, 저도 처음에 랜덤으로 로직을 짰지만, 마음에 들지 않는 부분이 있어 현재 로직으로 변경했지만 짜고보니 더 맘에 안들더라구요.. 용우님이 말씀 하신대로 랜덤이 그나마 제일 좋은 로직인 것 같습니다.

문구를 랜덤으로 반환해주는 로직으로 변경하도록 하겠습니다.

2022-06-27 14:38 UTC, honghyunin commented
> 전체적인 로직의 변경이 필요할꺼같습니다. 당장은 코드리뷰의 의미가 없을꺼같아 Request changes 하겠습니다.

로직을 랜덤으로 조회하는 방식으로 변경하였습니다. 확인 부탁드립니다 !

2022-06-28 03:12 UTC, Sinawe4 reviewed
고생하셨습니다
코멘트 확인 부탁드립니다!

2022-06-28 03:12 UTC, Sinawe4 commented on src/main/java/K/HBD/domain/card/service/Impl/CardServiceImpl.java
> +        String letter = sentenceRepository.findLetterByEmotion(emotion);
letter 인스턴스의 경우 참조가 일어나고 있지 않기때문에 바로 return 해주시는게 좋을꺼 같습니다!

2022-06-28 03:12 UTC, Sinawe4 commented on src/main/java/K/HBD/domain/card/service/Impl/CardServiceImpl.java
> +        String letter = sentenceRepository.findLetterByEmotion(emotion);
```java
return CardResponseDto.builder()
                .sentence(sentenceRepository.findLetterByEmotion(emotion))
                .image(BASE_URI + card.getFile())
                .name(card.getName())
                .emotion(emotion)
                .build();
```
이런식으로요!

2022-06-28 03:12 UTC, Sinawe4 commented on src/main/java/K/HBD/domain/enumType/Use.java
> +public enum Use {
해당 enum class는 삭제돼도 괜찮지 않나요?

2022-06-28 03:12 UTC, Sinawe4 commented on src/main/java/K/HBD/domain/sentence/Sentence.java
> +    private Use used_letter = Use.NOT_USED_LETTER;
해당 필드도 사라져도 될꺼같습니다

2022-06-28 03:12 UTC, Sinawe4 commented on src/main/java/K/HBD/domain/sentence/repository/SentenceCustomRepositoryImpl.java
> +        String letter = list.stream().map(Sentence::getLetter).findFirst().orElse(null);
하나의 데이터만 가져오려고 이런 식으로 Query 문을 작성하신 거 같은데,
sql에는 limit이라는 함수가 존재합니다 한번 알아보시면 좋을 거 같아요

2022-06-28 03:12 UTC, Sinawe4 commented on src/main/java/K/HBD/domain/sentence/service/Impl/SentenceServiceImpl.java
> +    private final static Use NOT_USED_LETTER = Use.NOT_USED_LETTER; //문구가 사용됐는 지 안됐는 지를 검사하기 위한 static Enum
해당 필드도 삭제해도 될꺼같습니다

2022-06-28 03:12 UTC, Sinawe4 commented on src/main/java/K/HBD/global/config/sentence/SetSentence.java
> +public class SetSentence {
해당 클래스는 테스트를 위해 존재하는건가요?
데이터를 자동으로 DB에 삽입해주는건 이해했습니다, 하지만 무슨 용도로 쓰이는지는 모르겠네요..

2022-06-28 04:16 UTC, honghyunin commented on src/main/java/K/HBD/global/config/sentence/SetSentence.java
> +public class SetSentence {
현재 AWS RDS를 사용하지 않고 있기 때문에 위 클래스가 존재하지 않으면 사용자에게 반환하기 위한 문구가 DB에 존재하지 않습니다. 따라서 db에 값을 직접 삽입해야 하기 때문에 서버가 실행되면 자동적으로 문구를 삽입해 놓는 것입니다.
물론 AWS RDS 사용할 경우 해당 값을 처음에 삽입해놓고 사용하면 될 것 같습니다.

2022-06-28 04:16 UTC, honghyunin commented on src/main/java/K/HBD/domain/sentence/Sentence.java
> +    private Use used_letter = Use.NOT_USED_LETTER;
수정하도록 하겠습니다!

2022-06-28 04:18 UTC, honghyunin commented on src/main/java/K/HBD/domain/card/service/Impl/CardServiceImpl.java
> +        String letter = sentenceRepository.findLetterByEmotion(emotion);
해당 레파지토리의 메소드에서 어떤 타입의 값을 가져오는 지에 대한 정보를 명시적으로 표기하기 위한 코드였습니다. 코드를 줄일 수 있지만 해당 부분에선 조금 더 명시적인 게 좋을 거 같습니다!

2022-06-28 04:19 UTC, honghyunin commented on src/main/java/K/HBD/domain/enumType/Use.java
> +public enum Use {
삭제하도록 하겠습니다!

2022-06-28 04:20 UTC, honghyunin commented on src/main/java/K/HBD/domain/sentence/repository/SentenceCustomRepositoryImpl.java
> +        String letter = list.stream().map(Sentence::getLetter).findFirst().orElse(null);
참고해서 수정하도록 하겠습니다!

2022-06-28 04:21 UTC, honghyunin commented on src/main/java/K/HBD/domain/sentence/service/Impl/SentenceServiceImpl.java
> +    private final static Use NOT_USED_LETTER = Use.NOT_USED_LETTER; //문구가 사용됐는 지 안됐는 지를 검사하기 위한 static Enum
삭제하도록 하겠습니다!

2022-06-28 05:00 UTC, Sinawe4 commented on src/main/java/K/HBD/domain/card/service/Impl/CardServiceImpl.java
> +        String letter = sentenceRepository.findLetterByEmotion(emotion);
제가 다른 프로젝트를 진행할 때, 해당 내용으로 의견 충돌이 있었는데요.
저희가 okky 라는 커뮤니티에 질문을 해보니, 많은 개발자분들이 인스턴스에 참조가 일어나지 않으면 바로 return 해주는게 좋다고 하시더라구요!

2022-06-28 05:01 UTC, Sinawe4 commented on src/main/java/K/HBD/domain/card/service/Impl/CardServiceImpl.java
> +        String letter = sentenceRepository.findLetterByEmotion(emotion);
> Member member = memberService.createMember()
> 
> return member;
> 
> return memberService.createMember();
> 
> 두 방식에 차이점은 없습니다 결과적으로는요.(로우수준 까지는 잘 모르겠네요 ^^;)
> 
> 다만, 개인적으로는 사용되지 않는 변수는 객체를 생성하지 않고 아래처럼 바로 리턴해주는게 낫다고 생각합니다.
> 
> 전자의 경우 추후 유지보수를 하다가 두 코드 사이에 이런 저런 코드들이 들어가게 되면 member라는 변수를 찾기 위해 추가적인 비용이 들텐데, 아래는 사용되지 않고 바로 리턴하기에 사이드 이펙트도 없을거고, 어떠한 작업이 필요하다면 그때 변수생성해서 작업을 하면 되겠죠.

실제 개발자 분이 남겨주신 코멘트입니다!

2022-06-28 05:06 UTC, honghyunin commented on src/main/java/K/HBD/domain/card/service/Impl/CardServiceImpl.java
> +        String letter = sentenceRepository.findLetterByEmotion(emotion);
> 해당 레파지토리의 메소드에서 어떤 타입의 값을 가져오는 지에 대한 정보를 명시적으로 표기하기 위한 코드였습니다. 코드를 줄일 수 있지만 해당 부분에선 조금 더 명시적인 게 좋을 거 같습니다!

옹 저도 항상 위처럼 생각했지만 가끔은 의심이 되기도 했습니다. 
그 의심에 근거가 되는 좋은 정보네요!
너무 클린 코드에 빠져 코드를 짜다가 실무에서 효율적이지 못한 코드가 될 수도 있겠다 라는 생각도 듭니다.
적당히 타협해서 작성하도록 유의하겠습니다 좋은 의견과 정보 감사합니다!

용우님이 말씀하신대로 수정하겠습니다!

2022-06-28 05:07 UTC, Sinawe4 commented on src/main/java/K/HBD/global/config/sentence/SetSentence.java
> +public class SetSentence {
h2를 사용중이신가요? h2도 로컬h2를 사용하면 데이터를 유지시킬 수 있지 않나요?

2022-06-28 05:12 UTC, honghyunin commented on src/main/java/K/HBD/global/config/sentence/SetSentence.java
> +public class SetSentence {
> h2를 사용중이신가요? h2도 로컬h2를 사용하면 데이터를 유지시킬 수 있지 않나요?

제가 따로 h2 db를 설치하지 않고 in-memory db로 사용하고 있어서요 ㅎ..
하지만 추후에 배포를 할 경우 해당 코드로 인한 문제가 생길 거 같네요
gitIgnore 하거나 삭제하도록 하겠습니다!

2022-06-28 05:20 UTC, Sinawe4 commented on src/main/java/K/HBD/global/config/sentence/SetSentence.java
> +public class SetSentence {
아이디어 자체는 되게 좋은거 같습니다!
Ignore만 해주시면 충분할꺼같네요!

2022-06-28 10:53 UTC, Sinawe4 approved these changes
피드백을 빠르게 적용시켰네요!
QueryDsl에서 limit도 제대로 적용시키셨습니다 👍 
고생하셨습니다!

2022-06-28 10:54 UTC, merged